development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: postgresql
  database: db/production.sqlite3

  production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5